# Generated by Django 2.1.1 on 2019-08-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='sign_end_time',
            field=models.DateTimeField(blank=True, help_text='签到结束时间', null=True, verbose_name='签到结束时间'),
        ),
        migrations.AddField(
            model_name='meet',
            name='sign_start_time',
            field=models.DateTimeField(blank=True, help_text='签到开始时间', null=True, verbose_name='签到开始时间'),
        ),
        migrations.AddField(
            model_name='meetrecord',
            name='sign_in',
            field=models.SmallIntegerField(choices=[(0, '未签到'), (1, '已签到'), (2, '超时未签到')], default=0, help_text='签到状态', verbose_name='签到状态'),
        ),
    ]
